name: Murderer
version: '1.0'
main: me.vetkover.itsmurderer.Murderer
api-version: 1.19

description: plugin for displaying suspected or confirmed players killers

commands:
  setmurder:
    description: set murderer status for user;
    usage: /setmurder <nickname> <status(SUS, Murder)>

  clearmurder:
    description: clear murderer status for user;
    usage: /clearmurder <nickname>

